/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.18.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ibm.aiops.connectors.models;

import com.google.gson.annotations.SerializedName;
import io.kubernetes.client.openapi.models.V1ObjectMeta;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * ConnectorComponent is the Schema for the connectorcomponents API
 */
@ApiModel(description = "ConnectorComponent is the Schema for the connectorcomponents API")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-09-02T16:30:48.596Z[Etc/UTC]")
public class V1beta1ConnectorComponent implements io.kubernetes.client.common.KubernetesObject {
  public static final String SERIALIZED_NAME_API_VERSION = "apiVersion";
  public static final String SERIALIZED_NAME_KIND = "kind";
  public static final String SERIALIZED_NAME_METADATA = "metadata";
  public static final String SERIALIZED_NAME_SPEC = "spec";
  public static final String SERIALIZED_NAME_STATUS = "status";
  @SerializedName(SERIALIZED_NAME_API_VERSION)
  private String apiVersion;
  @SerializedName(SERIALIZED_NAME_KIND)
  private String kind;
  @SerializedName(SERIALIZED_NAME_METADATA)
  private V1ObjectMeta metadata = null;
  @SerializedName(SERIALIZED_NAME_SPEC)
  private V1beta1ConnectorComponentSpec spec;
  @SerializedName(SERIALIZED_NAME_STATUS)
  private V1beta1ConnectorComponentStatus status;


  public V1beta1ConnectorComponent apiVersion(String apiVersion) {

    this.apiVersion = apiVersion;
    return this;
  }

  /**
   * APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
   *
   * @return apiVersion
   **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources")

  public String getApiVersion() {
    return apiVersion;
  }


  public void setApiVersion(String apiVersion) {
    this.apiVersion = apiVersion;
  }


  public V1beta1ConnectorComponent kind(String kind) {

    this.kind = kind;
    return this;
  }

  /**
   * Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
   *
   * @return kind
   **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds")

  public String getKind() {
    return kind;
  }


  public void setKind(String kind) {
    this.kind = kind;
  }


  public V1beta1ConnectorComponent metadata(V1ObjectMeta metadata) {

    this.metadata = metadata;
    return this;
  }

  /**
   * Get metadata
   *
   * @return metadata
   **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1ObjectMeta getMetadata() {
    return metadata;
  }


  public void setMetadata(V1ObjectMeta metadata) {
    this.metadata = metadata;
  }


  public V1beta1ConnectorComponent spec(V1beta1ConnectorComponentSpec spec) {

    this.spec = spec;
    return this;
  }

  /**
   * Get spec
   *
   * @return spec
   **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1beta1ConnectorComponentSpec getSpec() {
    return spec;
  }


  public void setSpec(V1beta1ConnectorComponentSpec spec) {
    this.spec = spec;
  }


  public V1beta1ConnectorComponent status(V1beta1ConnectorComponentStatus status) {

    this.status = status;
    return this;
  }

  /**
   * Get status
   *
   * @return status
   **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1beta1ConnectorComponentStatus getStatus() {
    return status;
  }


  public void setStatus(V1beta1ConnectorComponentStatus status) {
    this.status = status;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1beta1ConnectorComponent v1beta1ConnectorComponent = (V1beta1ConnectorComponent) o;
    return Objects.equals(this.apiVersion, v1beta1ConnectorComponent.apiVersion) &&
            Objects.equals(this.kind, v1beta1ConnectorComponent.kind) &&
            Objects.equals(this.metadata, v1beta1ConnectorComponent.metadata) &&
            Objects.equals(this.spec, v1beta1ConnectorComponent.spec) &&
            Objects.equals(this.status, v1beta1ConnectorComponent.status);
  }

  @Override
  public int hashCode() {
    return Objects.hash(apiVersion, kind, metadata, spec, status);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1beta1ConnectorComponent {\n");
    sb.append("    apiVersion: ").append(toIndentedString(apiVersion)).append("\n");
    sb.append("    kind: ").append(toIndentedString(kind)).append("\n");
    sb.append("    metadata: ").append(toIndentedString(metadata)).append("\n");
    sb.append("    spec: ").append(toIndentedString(spec)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

