/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.18.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ibm.aiops.connectors.models;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * Message type
 */
@ApiModel(description = "Message type")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-08-30T14:34:32.048Z[Etc/UTC]")
public class V1beta1ConnectorComponentStatusMessages {
    public static final String SERIALIZED_NAME_CLOUD_EVENT = "cloudEvent";
    @SerializedName(SERIALIZED_NAME_CLOUD_EVENT)
    private V1beta1ConnectorComponentStatusCloudEvent cloudEvent;


    public V1beta1ConnectorComponentStatusMessages cloudEvent(V1beta1ConnectorComponentStatusCloudEvent cloudEvent) {

        this.cloudEvent = cloudEvent;
        return this;
    }

    /**
     * Get cloudEvent
     *
     * @return cloudEvent
     **/
    @ApiModelProperty(required = true, value = "")

    public V1beta1ConnectorComponentStatusCloudEvent getCloudEvent() {
        return cloudEvent;
    }


    public void setCloudEvent(V1beta1ConnectorComponentStatusCloudEvent cloudEvent) {
        this.cloudEvent = cloudEvent;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        V1beta1ConnectorComponentStatusMessages v1beta1ConnectorComponentStatusMessages = (V1beta1ConnectorComponentStatusMessages) o;
        return Objects.equals(this.cloudEvent, v1beta1ConnectorComponentStatusMessages.cloudEvent);
    }

    @Override
    public int hashCode() {
        return Objects.hash(cloudEvent);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class V1beta1ConnectorComponentStatusMessages {\n");
        sb.append("    cloudEvent: ").append(toIndentedString(cloudEvent)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

